config/routes.rb
Rails.application.routes.draw do


  root 'pages#index'
  devise_for :users
  get 'pages/landing_page'
  get 'pages/about'


  resources :users do
    resources :purchasers, shallow: true
  end

  # resources :purchasers do          # Shallow
  #   resources :vendors, only: [:index, :new, :create]
  # end
  # resources :vendors, only: [:show, :edit, :update, :destroy]

  resources :purchasers do
    resources :vendors, shallow: true
  end

  get 'all_vendors', to: 'vendors#all_vendors'

  resources :vendors do
    resources :orders, shallow: true
  end

  get 'all_orders', to: 'orders#all_orders'

  get 'purchaser_orders', to: 'purchasers#purchaser_orders'
  # get 'purchaser_orders/:id', to: 'purchasers#purchaser_orders'
  get '/purchasers/:id/purchaser_orders', to: 'purchasers#purchaser_orders'



  # resources :purchasers do
  #   resources :orders
  # end

  resources :orders # For now

  get '/vendors/:id/orders', to: 'orders#index'



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :vendor
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: %i[ show edit update destroy ]
  before_action :orders_page


  def all_orders  # GET /all_orders
    @orders = Order.all
  end

  # GET /orders or /orders.json
  def index
    @vendor = Vendor.find(params[:vendor_id])
    @purchaser = @vendor.purchaser
    @orders = @vendor.orders.all
    @new_order = Order.new
    # @vendors = Vendor.all.order('name ASC')
  end

  # GET /orders/1 or /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
    @vendor = Vendor.find(params[:vendor_id])
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders or /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to purchasers_path, notice: "Order was successfully created." }
        format.json { render :show, status: :created, location: purchasers_path }
      else
        format.html { redirect_to purchasers_path, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1 or /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: "Order was successfully updated." }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1 or /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: "Order was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    def orders_page
      @orders_page = true
    end

    # Only allow a list of trusted parameters through.
    def order_params
      params.require(:order).permit(:name, :po_number, :date_recieved, :date_delivered, :distributed_by, :vendor_id)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<div class="p-4  border-t-2 border-r-2 border-b-2 border-l-4 border-gray-200 text-center">
  <div class="display-4" style="font-size:100%;">

<%= form_with(model: order, local: true) do |form| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
        <% order.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field p-2">
    <%= form.label :name %>
    <%= form.text_field :name, class:"bg-gray-200 form-control" %>
  </div>

  <div class="field p-2">
    <%= form.label :po_number, "PO Number" %>
    <%= form.number_field :po_number, class:"bg-gray-200 form-control" %>
  </div>

  <div class="p-2" style="">
    <%= form.label :date_recieved %>
    <%= form.date_field :date_recieved, as: :date, value: form.object.try(:strftime,"%m/%d/%Y"), class: 'form-control' %>
  </div>

  <div class="p-2" style="">
    <%= form.label :date_delivered %>
    <%= form.date_field :date_delivered, as: :date, value: form.object.try(:strftime,"%m/%d/%Y"), class: 'form-control' %>
  </div>


  <div class="field p-2">
    <%= form.label :distributed_by %>
    <%= form.text_field :distributed_by, class:"bg-gray-200 form-control" %>
  </div>

  <div class="field">
    <%= form.label :vendor_id %>
    <%= form.text_field :vendor_id, class:"bg-gray-200 form-control" %>
  </div>

  <div class="actions btn btn-success">
  <%= button_tag(type: 'submit') do %>
   Create Order
  <% end %>
  </div>
<% end %>

</div>
</div>

app/views/orders/_new_order.html.erb
<div class="p-4  border-t-2 border-r-2 border-b-2 border-l-4 border-gray-200 text-center">
  <div class="display-4" style="font-size:100%;">

<%#= form_with(model: order, local: true) do |form| %>
<%= form_with(model: [ vendor, vendor.orders.build ]) do |form| %>

  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
        <% order.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <!-- <% if vendor.id.present? %>
    <h1>VENDOR PRESENT: <%= vendor.name %></h1>
  <% else %>
    <h1>VENDOR MISSING :(</h1>
  <% end %>

  <% if purchaser.id.present? %>
    <h1>PURCHASER PRESENT: <%= purchaser.name %></h1>
  <% else %>
    <h1>PURCHASER MISSING :(</h1>
  <% end %> -->
  NEW ORDER PARTIAL
  <div class="field p-2">
    <%= form.label "Purchaser" %>
    <%= form.label "#{purchaser.name}", class: "form-control" %>
  </div>

  <div class="field p-2">
    <%= form.label "Vendor" %>
    <%= form.label "#{vendor.name}", class: "form-control" %>
    <%= form.hidden_field :vendor_id, value: vendor, class: "form-control", disabled: true %>
  </div>

  <div class="field p-2">
    <%= form.label :vendor_id, "Vendor ID"%>
    <%= form.text_field :vendor_id, value:vendor.id %>
  </div>

  <div class="field p-2">
    <%= form.label :name %>
    <%= form.text_field :name, class:" form-control" %>
  </div>

  <div class="field p-2">
    <%= form.label :po_number, "PO Number" %>
    <%= form.number_field :po_number, class:" form-control" %>
  </div>

  <div class="p-2" style="">
    <%= form.label :date_recieved %>
    <%= form.date_field :date_recieved, as: :date, value: form.object.try(:strftime,"%m/%d/%Y"), class: 'form-control' %>
  </div>

  <div class="p-2" style="">
    <%= form.label :date_delivered %>
    <%= form.date_field :date_delivered, as: :date, value: form.object.try(:strftime,"%m/%d/%Y"), class: 'form-control' %>
  </div>


  <div class="field p-2">
    <%= form.label :distributed_by %>
    <%= form.text_field :distributed_by, class:" form-control" %>
  </div>

  <!-- <div class="actions btn btn-success">
  <%#= button_tag(type: 'submit') do %>
   Create Order
  <%# end %>
  </div> -->

    <%= form.submit%>
<% end %>






</div>
</div>



<script>
$(document).ready(function(){ // Start of JS



}); // End of JS
</script>

app/views/orders/all_orders.html.erb
<style>

  @media (min-width: 640px) {
    table {
      display: inline-table !important;
    }

    thead tr:not(:first-child) {
      display: none;
    }
  }

  td:not(:last-child) {
    border-bottom: 0;
  }

  th:not(:last-child) {
    border-bottom: 2px solid rgba(0, 0, 0, .1);
  }
</style>

<div class="display-4" style="font-size:100%;">

  <div class="container">
    <div class="text-center p-4  border-t-2 border-r-2 border-b-2 border-l-4 border-gray-200">
      <div class="display-1" style="font-size:300%;">

        All Orders
        <!-- ******************************************** -->
        <!-- ******************************************** -->
        <!-- ******************************************** -->
        <br>
        <span class="display-1" style="font-size:40%;">(all_orders) </span>
        <!-- ******************************************** -->
        <!-- ******************************************** -->
        <!-- ******************************************** -->

      </div>
    </div>
    <br>
    <%= link_to 'Add Order', new_user_purchaser_path(current_user), class:"btn btn-success btn-block" %>
  </div>

  <div class="container pt-4">
  <div class="text-center p-4  border-t-2 border-r-2 border-b-2 border-l-4 border-gray-200">

      <div class=" container rounded-t-2xl ">
        <div class=" flex flex-col flex-no wrap w-full">
          <br>

          <div class="bg-teal-300 p-3 " >
            <span style="font-size:200%;">
              All Orders
            </span>
          </div>

        </div>
      </div>

  <!-- component -->
  <div class="flex items-center justify-center">

  	<div class="container">
      <table class="w-full flex flex-row flex-no-wrap sm:bg-white overflow-hidden sm:shadow-lg ">
  			<tbody class="flex-1 sm:flex-none">

          <% if @orders.count > 0 %>

          <% @orders.each do |order| %>

          				<tr class="flex flex-col flex-no wrap sm:table-row mb-2 sm:mb-0 bg-gray-100">

                    <td class="border-grey-light border hover:bg-gray-100 p-3">
                       <%= link_to "Order Details", order %>
                    </td>

                    <td class="border-grey-light border hover:bg-gray-100 p-3">
                      <strong>Purchaser: </strong>
                      <%#= link_to " #{order.purchaser.name}", purchasers_path(vendor.order.purchaser) %>
                      <% @purchaser = order.vendor.purchaser.id %>
                      <%= link_to order.vendor.purchaser.name, purchaser_path(@purchaser) %>
                    </td>

                    <td class="border-grey-light border hover:bg-gray-100 p-3">
                      <strong>Vendor: </strong> <%= link_to order.vendor.name, vendor_path(order.vendor) %>
                    </td>

          					<td class=" text-center border-grey-light border p-2">
                      <!-- Edit  -->
                      <!-- <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" class="bi bi-pencil-square " viewBox="0 0 16 16" style="height:10%; width:10%;" >
                        <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456l-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                        <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
                      </svg> -->

                      <!-- Delete  -->
                        <!-- <span class="hover:bg-gray-100 p-3 text-red-400 hover:text-red-600 hover:font-medium cursor-pointer">
                          <svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="trash-alt" class="svg-inline--fa fa-trash-alt fa-w-14" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512" style="height:10%; width:10%;">
                          <path fill="currentColor" d="M32 464a48 48 0 0 0 48 48h288a48 48 0 0 0 48-48V128H32zm272-256a16 16 0 0 1 32 0v224a16 16 0 0 1-32 0zm-96 0a16 16 0 0 1 32 0v224a16 16 0 0 1-32 0zm-96 0a16 16 0 0 1 32 0v224a16 16 0 0 1-32 0zM432 32H312l-9.4-18.7A24 24 0 0 0 281.1 0H166.8a23.72 23.72 0 0 0-21.4 13.3L136 32H16A16 16 0 0 0 0 48v32a16 16 0 0 0 16 16h416a16 16 0 0 0 16-16V48a16 16 0 0 0-16-16z"></path>
                        </svg>
                      </span> -->


                      <%= link_to 'Delete Order', order, method: :delete, data: { confirm: 'Are you sure? Once deleted you will never be able to recover this data.' }, class:"text-red-400 hover:text-red-600 hover:font-medium cursor-pointer" %>

                    </td>

          				</tr>

                  <% end %>

            <% else %>

            <tr class="flex flex-col flex-no wrap sm:table-row mb-2 sm:mb-0 bg-gray-100 ">
              <h5 class="bg-red-200 p-4 text-center">No Vendors Available.</h5>
            </tr>

            <% end %>

  			</tbody>
  		</table>

  	</div>
  </div>
</div>

</div>

<br>

</div>

</div>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<style>

  @media (min-width: 640px) {
    table {
      display: inline-table !important;
    }

    thead tr:not(:first-child) {
      display: none;
    }
  }

  td:not(:last-child) {
    border-bottom: 0;
  }

  th:not(:last-child) {
    border-bottom: 2px solid rgba(0, 0, 0, .1);
  }
</style>

<div class="display-4" style="font-size:100%;">

  <div class="container">
    <div class="text-center p-4  border-t-2 border-r-2 border-b-2 border-l-4 border-gray-200">
      <div class="display-1" style="font-size:300%;">

      <%= @vendor.name %> Orders
      <!-- ************************************************************** -->
      <!-- ************************************************************** -->
      <!-- ************************************************************** -->
      <br>
      <span class="display-1" style="font-size:40%;">(orders index) </span>
      <!-- ************************************************************** -->
      <!-- ************************************************************** -->
      <!-- ************************************************************** -->

      </div>
    </div>
    <br>
    <%= link_to 'Add Order', new_user_purchaser_path(current_user), class:"btn btn-success btn-block" %>
  </div>

  <div class="container pt-4">
  <div class="text-center p-4  border-t-2 border-r-2 border-b-2 border-l-4 border-gray-200">

      <div class=" container rounded-t-2xl ">
        <div class=" flex flex-col flex-no wrap w-full">
          <br>

          <div class="bg-teal-300 p-3 " >
            <span style="font-size:200%;">
              All <%= @vendor.name %> Orders
            </span>
          </div>

        </div>
      </div>

  <!-- component -->
  <div class="flex items-center justify-center">

  	<div class="container">
      <table class="w-full flex flex-row flex-no-wrap sm:bg-white overflow-hidden sm:shadow-lg ">
  			<tbody class="flex-1 sm:flex-none">

          <% if @orders.count > 0 %>

          <% @orders.each do |order| %>

          				<tr class="flex flex-col flex-no wrap sm:table-row mb-2 sm:mb-0 bg-gray-100">

                    <td class="border-grey-light border hover:bg-gray-100 p-3 ">
                      <div class="float-left">
                        <strong>Vendor: </strong> <%= link_to " #{order.vendor.name}", order.vendor %>
                        <br>
                        <strong>Purchaser: </strong> <%= link_to order.vendor.purchaser.name, purchaser_path(order.vendor.purchaser) %>

                      </div>
                    </td>


                    <td class="border-grey-light border hover:bg-gray-100 p-3">
                       <%= link_to "Order Details", order %>
                    </td>


                    <td class="border-grey-light border hover:bg-gray-100 p-3">
                      <strong>PO# </strong> <%= order.po_number %>
                    </td>


                    <td class="border-grey-light border hover:bg-gray-100 p-6">
                      <div class="float-left">
                        <strong>Delivered:</strong><br>
                        <% if order.date_delivered.present? != true %>
                          n/a
                        <% else%>
                        <%= " #{order.date_delivered.strftime("%m-%d-%y")}" %>
                        <% end %>
                        <br>
                        <strong>Recieved:</strong><br>
                        <% if order.date_recieved.present? != true %>
                          n/a
                        <% else%>
                        <%= " #{order.date_recieved.strftime("%m-%d-%y")}" %>
                        <% end %>

                      </div>
                    </td>

          					<td class=" text-center border-grey-light border p-2">


                      <!-- Edit  -->
                      <!-- <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" class="bi bi-pencil-square " viewBox="0 0 16 16" style="height:10%; width:10%;" >
                        <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456l-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                        <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
                      </svg> -->

                      <!-- Delete  -->
                        <!-- <span class="hover:bg-gray-100 p-3 text-red-400 hover:text-red-600 hover:font-medium cursor-pointer">
                          <svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="trash-alt" class="svg-inline--fa fa-trash-alt fa-w-14" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512" style="height:10%; width:10%;">
                          <path fill="currentColor" d="M32 464a48 48 0 0 0 48 48h288a48 48 0 0 0 48-48V128H32zm272-256a16 16 0 0 1 32 0v224a16 16 0 0 1-32 0zm-96 0a16 16 0 0 1 32 0v224a16 16 0 0 1-32 0zm-96 0a16 16 0 0 1 32 0v224a16 16 0 0 1-32 0zM432 32H312l-9.4-18.7A24 24 0 0 0 281.1 0H166.8a23.72 23.72 0 0 0-21.4 13.3L136 32H16A16 16 0 0 0 0 48v32a16 16 0 0 0 16 16h416a16 16 0 0 0 16-16V48a16 16 0 0 0-16-16z"></path>
                        </svg>
                      </span> -->


                      <%= link_to 'Delete Order', order, method: :delete, data: { confirm: 'Are you sure? Once deleted you will never be able to recover this data.' }, class:"text-red-400 hover:text-red-600 hover:font-medium cursor-pointer" %>

                    </td>

          				</tr>

                  <% end %>

            <% else %>

            <tr class="flex flex-col flex-no wrap sm:table-row mb-2 sm:mb-0 bg-gray-100 ">
              <h5 class="bg-red-200 p-4 text-center">No Orders Available.</h5>
            </tr>

            <% end %>

  			</tbody>
  		</table>

  	</div>
  </div>
</div>

</div>

<br>

</div>

</div>

app/views/orders/new.html.erb
<div class="display-1 bg-teal-300 text-center p-4 "style="font-size:200%;">
  New Order for <%= @vendor.name %>
</div>


<%= render 'form', order: @order %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p>
  <strong>Name:</strong>
  <%#= @order.description %>
</p>

<p>
  <strong>Po number:</strong>
  <%= @order.po_number %>
</p>

<p>
  <strong>Date recieved:</strong>
  <%= @order.date_recieved %>
</p>

<p>
  <strong>Date delivered:</strong>
  <%= @order.date_delivered %>
</p>

<p>
  <strong>Distributed by:</strong>
  <%= @order.distributed_by %>
</p>

<p>
  <strong>Vendor:</strong>
  <%= @order.vendor_id %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>