config/routes.rb
Rails.application.routes.draw do


  root 'pages#index'
  devise_for :users
  get 'pages/landing_page'
  get 'pages/about'


  resources :users do
    resources :purchasers, shallow: true
  end

  # resources :purchasers do          # Shallow
  #   resources :vendors, only: [:index, :new, :create]
  # end
  # resources :vendors, only: [:show, :edit, :update, :destroy]

  resources :purchasers do
    resources :vendors, shallow: true
  end

  get 'all_vendors', to: 'vendors#all_vendors'

  resources :vendors do
    resources :orders, shallow: true
  end

  get 'all_orders', to: 'orders#all_orders'

  get 'purchaser_orders', to: 'purchasers#purchaser_orders'
  # get 'purchaser_orders/:id', to: 'purchasers#purchaser_orders'
  get '/purchasers/:id/purchaser_orders', to: 'purchasers#purchaser_orders'



  # resources :purchasers do
  #   resources :orders
  # end

  resources :orders # For now

  get '/vendors/:id/orders', to: 'orders#index'



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/vendor.rb
class Vendor < ApplicationRecord
  belongs_to :purchaser
  has_many :orders
end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_vendor, only: %i[ show edit update destroy ]
  before_action :vendors_page


  # GET /all_vendors
  def all_vendors
    @vendors = Vendor.all.reverse
    @new_vendor = Vendor.new
  end


  # GET /vendors or /vendors.json
  def index
    @purchaser = Purchaser.find(params[:purchaser_id])
    @vendors = @purchaser.vendors.all.reverse
    @new_vendor = Vendor.new
  end

  # GET /vendors/1 or /vendors/1.json
  def show
    @vendor = Vendor.find(params[:id])
  end

  def new
    # @vendor = Vendor.new
    # @purchaser = Purchaser.find(params[:id])
    @purchaser = Purchaser.find(params[:purchaser_id])
    @vendor = @purchaser.vendors.build

  end

  def edit
    @vendor = Vendor.find(params[:id])
  end

  def create
    @vendor = Vendor.new(vendor_params)
    # byebug
    if @vendor.date_recieved.present? == false
      @vendor.date_recieved = DateTime.current.to_date
    end

    respond_to do |format|
      if @vendor.save
        format.html { redirect_to purchasers_path, notice: "Vendor was successfully created." }
        format.json { render :show, status: :created, location: purchasers_path }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @vendor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vendors/1 or /vendors/1.json
  def update
    respond_to do |format|
      if @vendor.update(vendor_params)
        format.html { redirect_to @vendor, notice: "Vendor was successfully updated." }
        format.json { render :show, status: :ok, location: @vendor }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @vendor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vendors/1 or /vendors/1.json
  def destroy
    @vendor.destroy
    respond_to do |format|
      format.html { redirect_to purchasers_path, notice: "Vendor was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.

    def vendors_page
      @vendors_page = true
    end

    def set_vendor
      @vendor = Vendor.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def vendor_params
      params.require(:vendor).permit(:name, :po_number, :date_recieved, :date_delivered, :distributed_by, :purchaser_id)
    end
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/views/vendors/_form.html.erb
<div class="p-4  border-t-2 border-r-2 border-b-2 border-l-4 border-gray-200 text-center">
  <div class="display-4" style="font-size:100%;">
  <%= form_with(model: vendor, local: true) do |form| %>
    <% if vendor.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(vendor.errors.count, "error") %> prohibited this vendor from being saved:</h2>
        <ul>
          <% vendor.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <%= form.label :vendor_id, "Purchaser" %>
    <div class="field p-2 form-control">
      <%#= form.text_field :vendor_id, class:" form-control" %>
      <%= form.collection_select :vendor_id, Purchaser.order(:name),:id,:name, prompt: "Select Purchaser"%>
    </div>

    <div class="field p-2">
      <%= form.label :name, "Vendor Name"%>
      <%= form.text_field :name, class:"bg-gray-200 form-control" %>
    </div>
    <%= form.hidden_field :purchaser_id %>
    <br>
    <div class="actions btn btn-success">
    <%= button_tag(type: 'submit') do %>
     Create Vendor
    <% end %>
    </div>
  <% end %>
  </div>
</div>

app/views/vendors/all_vendors.html.erb
<style>

  @media (min-width: 640px) {
    table {
      display: inline-table !important;
    }

    thead tr:not(:first-child) {
      display: none;
    }
  }

  td:not(:last-child) {
    border-bottom: 0;
  }

  th:not(:last-child) {
    border-bottom: 2px solid rgba(0, 0, 0, .1);
  }
</style>

<div class="display-4" style="font-size:100%;">

  <div class="container">
    <div class="text-center p-4  border-t-2 border-r-2 border-b-2 border-l-4 border-gray-200">
      <div class="display-1" style="font-size:300%;">

        All Vendors
        <!-- ************************************************************** -->
        <!-- ************************************************************** -->
        <!-- ************************************************************** -->
        <br>
        <span class="display-1" style="font-size:40%;">(all_vendors) </span>
        <!-- ************************************************************** -->
        <!-- ************************************************************** -->
        <!-- ************************************************************** -->

      </div>
    </div>
    <br>
    <%= link_to 'Add Vendor', new_user_purchaser_path(current_user), class:"btn btn-success btn-block" %>
  </div>

  <div class="container pt-4">
  <div class="text-center p-4  border-t-2 border-r-2 border-b-2 border-l-4 border-gray-200">

      <div class=" container rounded-t-2xl ">
        <div class=" flex flex-col flex-no wrap w-full">
          <br>

          <div class="bg-teal-300 p-3 " >
            <span style="font-size:200%;">
              All Vendors
            </span>
          </div>

        </div>
      </div>

  <!-- component -->
  <div class="flex items-center justify-center">

  	<div class="container">
      <table class="w-full flex flex-row flex-no-wrap sm:bg-white overflow-hidden sm:shadow-lg ">
  			<tbody class="flex-1 sm:flex-none">

          <% if @vendors.count > 0 %>

          <% @vendors.each do |vendor| %>

          				<tr class="flex flex-col flex-no wrap sm:table-row mb-2 sm:mb-0 bg-gray-100">

                    <td class="border-grey-light border hover:bg-gray-100 p-3">
                      <strong>Vendor:</strong>
                       <%= link_to " #{vendor.name}", vendor %>
                    </td>

                    <td class="border-grey-light border hover:bg-gray-100 p-3">
                      <strong>Purchaser: </strong> <%= link_to " #{vendor.purchaser.name}", vendor.purchaser %>
                    </td>



                    <td class="border-grey-light border hover:bg-gray-100 p-3">
                      <strong>Orders: </strong> <%= link_to " #{vendor.orders.count}", vendor_orders_path(vendor) %>
                    </td>


          					<td class=" text-center border-grey-light border p-2">


                      <!-- Edit  -->
                      <!-- <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" class="bi bi-pencil-square " viewBox="0 0 16 16" style="height:10%; width:10%;" >
                        <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456l-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                        <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
                      </svg> -->

                      <!-- Delete  -->
                        <!-- <span class="hover:bg-gray-100 p-3 text-red-400 hover:text-red-600 hover:font-medium cursor-pointer">
                          <svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="trash-alt" class="svg-inline--fa fa-trash-alt fa-w-14" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512" style="height:10%; width:10%;">
                          <path fill="currentColor" d="M32 464a48 48 0 0 0 48 48h288a48 48 0 0 0 48-48V128H32zm272-256a16 16 0 0 1 32 0v224a16 16 0 0 1-32 0zm-96 0a16 16 0 0 1 32 0v224a16 16 0 0 1-32 0zm-96 0a16 16 0 0 1 32 0v224a16 16 0 0 1-32 0zM432 32H312l-9.4-18.7A24 24 0 0 0 281.1 0H166.8a23.72 23.72 0 0 0-21.4 13.3L136 32H16A16 16 0 0 0 0 48v32a16 16 0 0 0 16 16h416a16 16 0 0 0 16-16V48a16 16 0 0 0-16-16z"></path>
                        </svg>
                      </span> -->

                      <div class="p-4 text-red-400"> Delete </div>
                      <%#= link_to 'Delete Vendor', vendor, method: :delete, data: { confirm: 'Are you sure? Once deleted you will never be able to recover this data.' }, class:"text-red-400 hover:text-red-600 hover:font-medium cursor-pointer" %>

                    </td>

          				</tr>

                  <% end %>

            <% else %>

            <tr class="flex flex-col flex-no wrap sm:table-row mb-2 sm:mb-0 bg-gray-100 ">
              <h5 class="bg-red-200 p-4 text-center">No Vendors Available.</h5>
            </tr>

            <% end %>

  			</tbody>
  		</table>

  	</div>
  </div>
</div>

</div>

<br>

</div>

</div>

app/views/vendors/edit.html.erb
<h1>Editing Vendor</h1>

<%= render 'form', vendor: @vendor %>

<%= link_to 'Show', @vendor %> |
<%= link_to 'Back', :back %>

app/views/vendors/index.html.erb
<style>

  @media (min-width: 640px) {
    table {
      display: inline-table !important;
    }

    thead tr:not(:first-child) {
      display: none;
    }
  }

  td:not(:last-child) {
    border-bottom: 0;
  }

  th:not(:last-child) {
    border-bottom: 2px solid rgba(0, 0, 0, .1);
  }
</style>

<div class="display-4" style="font-size:100%;">


  <div class="text-center p-4  border-t-2 border-r-2 border-b-2 border-l-4 border-gray-200">
    <div class="display-1" style="font-size:300%;">All Vendors</div>
  </div>

  <br>
  <%= link_to 'Add New Vendor', new_user_purchaser_path(current_user), class:"btn btn-success btn-block" %>

<br>




<% @vendors.each do |vendor| %>

<!-- <div class="p-4 bg-gray-100"> -->
<div class="p-4  border-t-2 border-r-2 border-b-2 border-l-4 border-gray-200">

  <div class=" container rounded-t-2xl ">
    <div class=" flex flex-col flex-no wrap w-full">
      <br>

      <!-- <div class="bg-teal-400 p-3"> Purchased by: <%= vendor.name %> </div> -->
      <!-- <%= link_to "Purchased by #{vendor.name}", vendor, class:"bg-teal-400 p-3 btn"%> -->

      <button type="button" name="button" class="bg-teal-300 p-3 btn" >
        <div>
          <%= link_to " #{vendor.name.capitalize}", vendor, class:"display-4",style:"width:100%; font-size:200%;" %>
          <!-- <%= link_to "#{vendor.name.capitalize}", vendor %> -->

        </div>
      </button>

    </div>
  </div>

  <!-- component -->
  <div class="flex items-center justify-center">

  	<div class="container -mt-4">
      <!-- <table class="w-full flex flex-row flex-no-wrap sm:bg-white rounded-lg overflow-hidden sm:shadow-lg my-1"> -->
      <table class="w-full flex flex-row flex-no-wrap sm:bg-white overflow-hidden sm:shadow-lg my-1">
  			<tbody class="flex-1 sm:flex-none">



          				<tr class="flex flex-col flex-no wrap sm:table-row mb-2 sm:mb-0 bg-gray-100">

                    <td class="border-grey-light border hover:bg-gray-100 p-3">

                      <strong>Purchased by:</strong>
                       <%= link_to " #{vendor.purchaser.name}", vendor.purchaser %>
                    </td>

                    <td class="border-grey-light border hover:bg-gray-100 p-3">
                      <strong>PO: </strong> <%= vendor.po_number %>
                    </td>

                    <td class="border-grey-light border hover:bg-gray-100 p-3"><strong>Distributor: </strong> <%= vendor.distributed_by %></td>

                    <td class="border-grey-light border hover:bg-gray-100 p-3">
                      <strong>Recieved:</strong>
                      <%= " #{vendor.date_recieved.strftime("%m-%d-%y")}" %>
                    </td>

                    <td class="border-grey-light border hover:bg-gray-100 p-3">
                        <strong>Delivered:</strong>
                        <% if vendor.date_delivered.present? != true %>
                          n/a
                        <% else%>
                        <%= " #{vendor.date_delivered.strftime("%m-%d-%y")}" %>
                        <% end %>
                    </td>

          					<td class=" text-center border-grey-light border hover:bg-gray-100 p-3 text-red-400 hover:text-red-600 hover:font-medium cursor-pointer">
                      <%= link_to 'Delete', vendor, method: :delete, data: { confirm: 'Are you sure? Once deleted you will never be able to recover this data.' } %>
                    </td>

          				</tr>



  			</tbody>
  		</table>

      <br>
      <br>
      <div class="container text-center" style:"object-fit: contain;">

        <%= link_to 'View Order', vendor_path(vendor), class:"btn btn-success " %>


      </div>

















  	</div>
  </div>

  <br>



</div>

<br>
<br>



<% end %>

</div>

app/views/vendors/new.html.erb
<!-- <div type="button" name="button" class="bg-teal-300 p-3 " >
</div> -->


<div class="display-1 bg-teal-300 text-center p-4 "style="font-size:200%;">
    New Vendor for <%= @purchaser.name%>
</div>

<%= render 'form', vendor: @vendor %>

app/views/vendors/show.html.erb
<style>

  @media (min-width: 640px) {
    table {
      display: inline-table !important;
    }

    thead tr:not(:first-child) {
      display: none;
    }
  }

  td:not(:last-child) {
    border-bottom: 0;
  }

  th:not(:last-child) {
    border-bottom: 2px solid rgba(0, 0, 0, .1);
  }
</style>

<div class="display-4" style="font-size:100%;">

  <div class="container">
    <div class="text-center p-4  border-t-2 border-r-2 border-b-2 border-l-4 border-gray-200">
      <div class="display-1" style="font-size:300%;">
         Vendor: <%= @vendor.name.capitalize %>

         <div class="display-1" style="font-size:50%;">
           Purchased by: <%= link_to "#{@vendor.purchaser.name}", purchaser_path(@vendor.purchaser)  %>
         </div>
      </div>

      <br>
      <span class="display-1" style="font-size:100%;">(Vendors Show) </span>


    </div>

    <br>

    <!-- Three button col -->
    <div>
      <%= link_to 'Add Order', new_vendor_order_path(@vendor), class:"btn btn-success btn-block" %>
    </div>

  </div>



  <div class="container pt-4">
  <div class="text-center p-4  border-t-2 border-r-2 border-b-2 border-l-4 border-gray-200">


          <div class=" container rounded-t-2xl ">
            <div class=" flex flex-col flex-no wrap w-full">
              <br>

              <div class="bg-teal-300 p-3 " >
                <span style="font-size:200%;">
                  All <%= @vendor.name %> Orders
                </span>
              </div>

            </div>
          </div>

      <!-- component -->
      <div class="flex items-center justify-center">

      	<div class="container">
          <table class="w-full flex flex-row flex-no-wrap sm:bg-white overflow-hidden sm:shadow-lg ">
      			<tbody class="flex-1 sm:flex-none">

              <% if @vendor.orders.count > 0 %>

              <% @vendor.orders.each do |vendor| %>

              				<tr class="flex flex-col flex-no wrap sm:table-row mb-2 sm:mb-0 bg-gray-100">

                        <td class="border-grey-light border hover:bg-gray-100 p-3">

                          <strong>Vendor:</strong>
                           <%= link_to " #{vendor.name}", vendor %>
                        </td>

                        <td class="border-grey-light border hover:bg-gray-100 p-3">
                          <strong>PO: </strong> <%= vendor.po_number %>
                        </td>

                        <td class="border-grey-light border hover:bg-gray-100 p-3"><strong>Distributor: </strong> <%= vendor.distributed_by %></td>

                        <td class="border-grey-light border hover:bg-gray-100 p-3">
                          <strong>Recieved:</strong><%= " #{vendor.date_recieved.strftime("%m-%d-%y")}" %>
                        </td>

                        <td class="border-grey-light border hover:bg-gray-100 p-3">
                            <strong>Delivered:</strong>
                            <% if vendor.date_delivered.present? != true %>
                              n/a
                            <% else%>
                            <%= " #{vendor.date_delivered.strftime("%m-%d-%y")}" %>
                            <% end %>
                        </td>

              					<td class=" text-center border-grey-light border">


                          <!-- Edit  -->
                          <!-- <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" class="bi bi-pencil-square " viewBox="0 0 16 16" style="height:10%; width:10%;" >
                            <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456l-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                            <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
                          </svg> -->

                          <!-- Delete  -->
                            <!-- <span class="hover:bg-gray-100 p-3 text-red-400 hover:text-red-600 hover:font-medium cursor-pointer">
                              <svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="trash-alt" class="svg-inline--fa fa-trash-alt fa-w-14" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512" style="height:10%; width:10%;">
                              <path fill="currentColor" d="M32 464a48 48 0 0 0 48 48h288a48 48 0 0 0 48-48V128H32zm272-256a16 16 0 0 1 32 0v224a16 16 0 0 1-32 0zm-96 0a16 16 0 0 1 32 0v224a16 16 0 0 1-32 0zm-96 0a16 16 0 0 1 32 0v224a16 16 0 0 1-32 0zM432 32H312l-9.4-18.7A24 24 0 0 0 281.1 0H166.8a23.72 23.72 0 0 0-21.4 13.3L136 32H16A16 16 0 0 0 0 48v32a16 16 0 0 0 16 16h416a16 16 0 0 0 16-16V48a16 16 0 0 0-16-16z"></path>
                            </svg>
                          </span> -->

                          <div class="p-4 text-red-400"> Delete </div>
                          <%#= link_to 'Delete', vendor, method: :delete, data: { confirm: 'Are you sure? Once deleted you will never be able to recover this data.' }, class:"text-red-400 hover:text-red-600 hover:font-medium cursor-pointer" %>

                        </td>

              				</tr>

                      <% end %>

                <% else %>

                <tr class="flex flex-col flex-no wrap sm:table-row mb-2 sm:mb-0 bg-gray-100 ">
                  <h5 class="bg-red-200 p-4 text-center">No Orders Available.</h5>
                </tr>

                <% end %>

      			</tbody>
      		</table>

      	</div>
      </div>
    </div>

</div>


  <br>



</div>




</div>